{"../eqc/*", [{parse_transform, eqc_cover}, {parse_transform, pulse_instrument}]}.
{"../src/*", [ {parse_transform, eqc_cover}, {parse_transform, pulse_instrument}
	     , {pulse_replace_module, [{application, pulse_application}]}
	     , {pulse_replace_module, [{application_controller, pulse_application_controller}]}
	     , {pulse_replace_module, [{application_master, pulse_application_master}]}
	     , {pulse_replace_module, [{application_starter, pulse_application_starter}]}
	     , {pulse_replace_module, [{gen, pulse_gen}]}
	     , {pulse_replace_module, [{gen_event, pulse_gen_event}]}
	     , {pulse_replace_module, [{gen_fsm, pulse_gen_fsm}]}
	     , {pulse_replace_module, [{gen_statem, pulse_gen_statem}]}
	     , {pulse_replace_module, [{gen_server, pulse_gen_server}]}
	     , {pulse_replace_module, [{proc_lib, pulse_proc_lib}]}
	     , {pulse_replace_module, [{supervisor, pulse_supervisor}]}
	     , {pulse_replace_module, [{sys, pulse_sys}]} ]}.
